# Generated by Django 5.2.8 on 2025-11-22 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fridgeitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.IntegerField(default=2000, verbose_name='Дневная норма калорий')),
                ('allergies', models.TextField(blank=True, verbose_name='Аллергии')),
                ('dietary_restrictions', models.TextField(blank=True, verbose_name='Диетические ограничения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Предпочтение пользователя',
                'verbose_name_plural': 'Предпочтения пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ['name'], 'verbose_name': 'Кухня', 'verbose_name_plural': 'Кухни'},
        ),
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'ordering': ['-date'], 'verbose_name': 'Дневное меню', 'verbose_name_plural': 'Дневные меню'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='fridgeitem',
            options={'ordering': ['category', 'added_date'], 'verbose_name': 'Продукт в холодильнике', 'verbose_name_plural': 'Продукты в холодильнике'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['completed', 'created_at'], 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.AddField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cuisines/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='dish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название кухни'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_menus', to='app.dish', verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_menus', to='app.dish', verbose_name='Ужин'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_menus', to='app.dish', verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=0, help_text='Калории на порцию', verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooking_time',
            field=models.IntegerField(help_text='Время в минутах', verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='app.cuisine', verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='medium', max_length=50, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Овощи'), ('fruits', 'Фрукты'), ('meat', 'Мясо'), ('fish', 'Рыба'), ('dairy', 'Молочные продукты'), ('grains', 'Крупы и злаки'), ('spices', 'Специи и приправы'), ('beverages', 'Напитки'), ('other', 'Другое')], default='other', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='ingredient',
            field=models.CharField(max_length=200, verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['name'], name='app_dish_name_d2c793_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['cuisine'], name='app_dish_cuisine_e8495f_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['difficulty'], name='app_dish_difficu_22efda_idx'),
        ),
        migrations.AddIndex(
            model_name='fridgeitem',
            index=models.Index(fields=['user', 'category'], name='app_fridgei_user_id_cea109_idx'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_cuisines',
            field=models.ManyToManyField(blank=True, to='app.cuisine', verbose_name='Предпочтительные кухни'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
